/* Nasr School Management System — translation dictionaries
 * Every user-facing string in index.html is referenced by key via
 * data-i18n="<key>" (text) or data-i18n-<attr>="<key>" (attribute value).
 * Keys are identical in both dictionaries; add to both when adding copy.
 */

const AR = {
  authNoLib: 'لم تُحمَّل مكتبة الاتصال بقاعدة البيانات. تأكّد من اتصالك بالإنترنت ثم أعد تحميل الصفحة.',
  authBadCreds: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.', authUnconfirmed: 'لم يُفعّل هذا البريد بعد — افتح رسالة التأكيد في بريدك.', authRateLimit: 'محاولات كثيرة متتالية. انتظر قليلاً ثم أعد المحاولة.', authOffline: 'تعذّر الوصول إلى الخادم. تحقّق من اتصالك.', authFailed: 'تعذّر تسجيل الدخول.', authMissing: 'أدخل البريد الإلكتروني وكلمة المرور.', saving: 'جارٍ الحفظ…', saveFailed: 'تعذّر الحفظ.', dbMissing: 'قاعدة البيانات غير مهيّأة بعد.',
  crumbAria: 'مسار التنقل',
  mock: 'نموذج الشاشات', navVisitor: 'الصفحة العامة', navLogin: 'تسجيل الدخول', navAdmin: 'لوحة المدير', navStaff: 'لوحة المعلم', navParent: 'لوحة وليّ الأمر',
  stLoading: 'حالة التحميل', stEmpty: 'حالة فارغة', stStudent: 'نافذة إضافة طالب', stTeacher: 'نافذة إضافة معلم',
  brand: 'مجمع مدارس النصر', brandSub: 'أقسام مستقلة للبنين والبنات · روضة — ثاني عشر',
  mAbout: 'عن المجمع', mLevels: 'المراحل والأقسام', mFees: 'الرسوم', mContact: 'تواصل معنا', loginCtaShort: 'دخول أولياء الأمور والمعلمين',
  vBadge: 'التسجيل مفتوح للعام 1448هـ / 2026م',
  vTitle: 'تعليم متين وبيئة مدرسية منظّمة — لكل مرحلة قسمها المستقل',
  vText: 'مجمع مدارس النصر يضم قسمين منفصلين تماماً للبنين والبنات، بمبانٍ وكوادر تعليمية وإدارة مستقلة لكل قسم، من الروضة حتى الثاني عشر.',
  vApply: 'تقديم طلب / استفسار', vBrochure: 'تحميل الدليل التعريفي',
  vStudents: 'طالب وطالبة', vStaff: 'كادر تعليمي', vYears: 'عاماً من العطاء', vClasses: 'فصل دراسي',
  imgMain: 'صورة المبنى الرئيسي — [ ضع هنا صورة أفقية عالية الدقة ]',
  boys: 'قسم البنين', girls: 'قسم البنات',
  boysText: 'مبنى مستقل بكادر تعليمي وإداري من الرجال، وأنشطة رياضية ومختبرات علمية مخصصة.',
  girlsText: 'مبنى مستقل بكادر تعليمي وإداري من النساء، مع قاعات أنشطة ومعامل حاسب مخصصة.',
  lvlKgB: 'الروضة والتمهيدي · بنين', lvlKgG: 'الروضة والتمهيدي · بنات', lvlPri: 'الابتدائية (1 — 6)', lvlMid: 'المتوسطة (7 — 9)', lvlHigh: 'الثانوية (10 — 12)',
  quick: 'معلومات سريعة', qDay: 'اليوم الدراسي', qBus: 'النقل المدرسي', qBusV: 'متوفر لكل الأحياء', qSize: 'عدد الطلاب بالفصل', qSizeV: '28 كحد أقصى', qFees: 'الرسوم السنوية', qFeesV: 'من 8,400 ر.س',
  applyTitle: 'تقديم طلب أو استفسار',
  applyText: 'أرسل بياناتك وسيتواصل معك قسم التسجيل خلال يوم عمل واحد لتحديد موعد زيارة للقسم المناسب.',
  contactTitle: 'معلومات التواصل', contactPhone: 'هاتف قسم التسجيل: 011 456 7890', contactMail: 'البريد: info@nasr.edu.sa', contactAddr: 'العنوان: طريق الملك عبدالعزيز، حي النخيل، الرياض',
  mapPh: 'خريطة الموقع — [ خريطة تفاعلية ]',
  fName: 'اسم مقدّم الطلب', fNamePh: 'محمد العتيبي', fPhone: 'رقم الجوال', fAge: 'عمر الطالب / الطالبة', fAgePh: '9 سنوات', fCampus: 'القسم المطلوب',
  fMsg: 'رسالتك أو استفسارك', fMsgPh: 'أرغب في معلومات عن التسجيل في الصف الرابع…', fConsent: 'أوافق على استخدام بياناتي للتواصل بشأن الطلب', fSubmit: 'إرسال الطلب',
  haveAcc: 'هل لديك حساب؟', loginWord: 'تسجيل الدخول',
  footerRights: '© 1448هـ / 2026م مجمع مدارس النصر — جميع الحقوق محفوظة', privacy: 'سياسة الخصوصية', jobs: 'الوظائف',
  lTitle: 'منصّة واحدة لإدارة الطلاب والمعلمين وأولياء الأمور', lText: 'الحضور، الدرجات، الجداول، والرسوم الدراسية — في مكان واحد آمن ومنظّم.',
  loginTitle: 'تسجيل الدخول', loginSub: 'اختر نوع الحساب ثم أدخل بياناتك',
  roleAdmin: 'مدير', roleStaff: 'معلم / موظف', roleParent: 'وليّ أمر',
  emailLabel: 'البريد الإلكتروني أو رقم الهوية', pwLabel: 'كلمة المرور', remember: 'تذكّرني', forgot: 'نسيت كلمة المرور؟',
  loginCta: 'دخول إلى لوحة التحكم', loginNote: 'سيتم توجيهك تلقائياً حسب نوع الحساب المحدد.',
  secAdmin: 'الإدارة', mOverview: 'نظرة عامة', mStudents: 'الطلاب', mStaffNav: 'المعلمون والموظفون', mClasses: 'الفصول والجداول', mReports: 'التقارير والتحليلات', mFinance: 'الرسوم والمالية', mCalendarNav: 'التقويم الدراسي', mLogNav: 'سجل النشاط', secSystem: 'النظام', mSettings: 'الإعدادات والصلاحيات',
  adminName: 'عبدالله السالم', adminRole: 'مدير المجمع',
  ovTitle: 'نظرة عامة', termLine: 'الفصل الدراسي الأول 1448هـ / 2026م', searchPh: 'ابحث عن طالب أو معلم…', addStudent: '+ إضافة طالب',
  notifTitle: 'الإشعارات', nb1: '23 فاتورة متأخرة السداد', nb1s: 'المالية · قبل ساعة', nb2: '7 حالات غياب اليوم بحاجة لمتابعة', nb2s: 'الحضور · قبل 3 ساعات', nb3: '4 أسئلة من أولياء الأمور بلا رد', nb3s: 'الرسائل · اليوم', notifAll: 'عرض كل الإشعارات',
  kStudents: 'إجمالي الطلاب', kStaff: 'المعلمون والموظفون', kClasses: 'الفصول الدراسية', kRevenue: 'إيرادات الفصل',
  tStudents: '▲ 3.2% عن الشهر الماضي', tStaff: '4 وظائف قيد التعيين', tClasses: 'متوسط 30 طالباً للفصل', tRevenue: 'متأخرات: 96,400 ر.س', millionUnit: ' مليون ر.س',
  attTitle: 'نسبة الحضور الأسبوعية', attAvg: 'متوسط 94%', sun: 'الأحد', mon: 'الاثنين', tue: 'الثلاثاء', wed: 'الأربعاء', thu: 'الخميس',
  alerts: 'تنبيهات تحتاج إجراء', al1: '23 فاتورة متأخرة السداد', al1s: 'بقيمة 96,400 ر.س — مراجعة قسم المالية', al2: '7 طلبات تسجيل جديدة', al2s: 'في انتظار موافقة الإدارة', al3: 'فصلان بدون معلم بديل غداً', al3s: 'الصف الرابع (ب) · الصف السادس (أ)', allAlerts: 'عرض كل التنبيهات',
  qaTitle: 'إشراف أسئلة أولياء الأمور', qaSub: 'إحصاءات مجمّعة لكل قسم — الإدارة لا تدخل محادثات الموظفين', qaReport: 'تقرير التواصل الكامل',
  qaPendBoys: 'أسئلة معلّقة — بنين', qaPendGirls: 'أسئلة معلّقة — بنات', qaAvgTime: 'متوسط زمن الرد', qaOver: 'تجاوزت 24 ساعة', hoursUnit: ' ساعات',
  calTitle: 'التقويم الدراسي', calSub: 'العطل والاختبارات والأنشطة — سبتمبر / أكتوبر', calFull: 'التقويم الكامل',
  tHoliday: 'عطلة', tExam: 'اختبار', tEvent: 'نشاط',
  ev1: 'اجتماع أولياء الأمور', ev1d: 'الخميس 12 سبتمبر · 5 — 7 م', ev2: 'اختبارات الوحدة الثانية', ev2d: 'الأحد 15 — الأربعاء 18 سبتمبر', ev3: 'اليوم الوطني — عطلة رسمية', ev3d: 'الأربعاء 23 سبتمبر', ev4: 'رحلة متحف العلوم', ev4d: 'الاثنين 5 أكتوبر · قسم البنين',
  cmpTitle: 'تحليلات مقارنة', cmpSub: 'قسم البنين مقابل قسم البنات · الفصل الحالي مقابل السابق',
  cmpAvg: 'المعدل العام', cmpAtt: 'نسبة الحضور', cmpPass: 'نسبة الاجتياز', cmpTermNow: 'الفصل الحالي', cmpTermPrev: 'الفصل السابق', exportPdf: 'تصدير PDF', exportXls: 'تصدير Excel',
  staffMgmt: 'إدارة المعلمين والموظفين', staffMgmtSub: 'القسمان يُداران بشكل مستقل', boysCount: 'قسم البنين (41)', girlsCount: 'قسم البنات (45)', addTeacher: '+ إضافة معلم',
  thTeacher: 'المعلم', thSubject: 'التخصص', thCampus: 'القسم', thClassesCol: 'الفصول', thActions: 'إجراءات', edit: 'تعديل', del: 'حذف',
  t1: 'خالد عبدالرحمن الشمري', t2: 'هند ناصر الزهراني', subjScience: 'علوم', subjMath: 'رياضيات', cls5: '5 فصول', cls6: '6 فصول', tagBoys: 'بنين', tagGirls: 'بنات',
  recent: 'أحدث الطلاب المسجّلين', fAll: 'الكل', fPri: 'المرحلة الابتدائية', fMid: 'المرحلة المتوسطة',
  thStudent: 'الطالب', thGradeCol: 'الصف', thGuardian: 'وليّ الأمر', thFeesCol: 'حالة الرسوم',
  s1: 'نورة محمد العتيبي', s2: 'سلمان عبدالعزيز القحطاني', s3: 'ريم فهد الدوسري', g1: 'محمد العتيبي', g2: 'عبدالعزيز القحطاني', g3: 'فهد الدوسري',
  gr4a: 'الرابع (أ)', gr6b: 'السادس (ب)', gr2c: 'الثاني (ج)', paid: 'مسدّدة', lateFee: 'قسط متأخر', underReview: 'قيد المراجعة',
  loadingStudents: 'جارٍ تحميل بيانات الطلاب…', emptyTitle: 'لا توجد نتائج مطابقة', emptyText: 'لم يتم العثور على طلاب بهذه الفلاتر. جرّب تغيير المرحلة أو أضف طالباً جديداً للبدء.',
  logTitle: 'سجل النشاط الإداري', logSub: 'من غيّر ماذا ومتى', logAll: 'السجل الكامل',
  lg1: 'عبدالله السالم', lg1w: 'عدّل رسوم الصف السادس (ب)', lg1t: 'اليوم 10:42 ص', lg2: 'ريما الحميد', lg2w: 'أضافت معلمة إلى قسم البنات', lg2t: 'اليوم 09:15 ص', lg3: 'طلال المطيري', lg3w: 'صدّر تقرير حضور قسم البنين', lg3t: 'أمس 01:20 م',
  secDaily: 'يومي', mMySchedule: 'جدولي', mAttendance: 'تسجيل الحضور', mGradesNav: 'إدخال الدرجات', mMyClasses: 'فصولي', secComms: 'التواصل', mMessages: 'الرسائل والتعاميم', mParentQ: 'أسئلة أولياء الأمور', mTasks: 'مهامي',
  chatSecGirls: 'محادثة القسم — بنات', chatGirlsNav: 'محادثة كادر البنات', noteGirls: 'حسابك مرتبط بقسم البنات — محادثة كادر البنين غير متاحة.',
  chatSecBoys: 'محادثة القسم — بنين', chatBoysNav: 'محادثة كادر البنين', noteBoys: 'حسابك مرتبط بقسم البنين — محادثة كادر البنات غير متاحة.',
  staffNameG: 'هند ناصر', staffRoleG: 'معلمة رياضيات · قسم البنات', staffNameB: 'خالد الشمري', staffRoleB: 'معلم علوم · قسم البنين',
  greetG: 'صباح الخير، هند', greetB: 'صباح الخير، خالد', staffDay: 'الأحد 8 سبتمبر · لديك 4 حصص وفصل واحد بحاجة لتسجيل الحضور', markNow: 'تسجيل حضور الحصة الحالية',
  weekTitle: 'جدول الأسبوع', lessonsWeek: '20 حصة أسبوعياً',
  subjMathShort: 'رياضيات', freePeriod: 'حصة فراغ', breakDuty: 'إشراف الفسحة', deptMeeting: 'اجتماع القسم', mathActivity: 'نشاط رياضيات',
  cls4a: 'الرابع (أ)', cls4b: 'الرابع (ب)', cls5a: 'الخامس (أ)', cls5b: 'الخامس (ب)', cls6a: 'السادس (أ)', cls6b: 'السادس (ب)',
  pqTitle: 'أسئلة أولياء الأمور', pqPending: '4 معلّقة', pqTabPending: 'معلّقة', pqTabAnswered: 'مجابة', pqSla: 'وقت الرد المتوقع لديك: خلال 24 ساعة',
  pq1: 'محمد العتيبي', pq1meta: 'وليّ أمر نورة · الرابع (أ)', pq1txt: 'هل توجد تمارين إضافية للقسمة الطويلة يمكن العمل عليها في المنزل؟', pq1st: 'معلّق · 3 ساعات',
  pq2: 'فهد الدوسري', pq2meta: 'وليّ أمر ريم · الثاني (ج)', pq2txt: 'متى موعد اختبار الوحدة الثالثة؟', pq2st: 'معلّق · 11 ساعة',
  pq3: 'سعاد القحطاني', pq3meta: 'وليّة أمر لمى · الخامس (ب)', pq3txt: 'شكراً على التوضيح بشأن الواجب الأسبوعي.', pq3st: 'تم الرد',
  pqReply: 'رد', pqEscalate: 'تحويل للإدارة',
  chatGTitle: 'محادثة كادر قسم البنات', chatGSub: '14 عضوة · مساحة خاصة بقسم البنات فقط',
  cg1n: 'أ. لمياء القرني', cg1m: 'صباح الخير، توزيع مراقبة اختبار الوحدة معلّق على لوحة القسم.', cg2n: 'أ. ريما الحميد — وكيلة القسم', cg2m: 'تذكير: رصد الدرجات ينتهي غداً الساعة 2 مساءً.', cgMe: 'تم، سأنتهي من رصد الرابع (أ) اليوم.', chatGPh: 'اكتبي رسالة لكادر قسم البنات…',
  chatBTitle: 'محادثة كادر قسم البنين', chatBSub: '12 عضواً · مساحة خاصة بقسم البنين فقط',
  cb1n: 'أ. خالد الشمري', cb1m: 'مختبر العلوم محجوز للحصة الثالثة اليوم.', cb2n: 'أ. طلال المطيري — وكيل القسم', cb2m: 'من يستطيع تغطية حصة الصف السادس (أ) غداً؟', cbMe: 'أستطيع تغطيتها، حصتي الثانية فراغ.', chatBPh: 'اكتب رسالة لكادر قسم البنين…',
  me: 'أنا', send: 'إرسال',
  attMark: 'تسجيل الحضور —', incomplete: 'غير مكتمل', period1: 'الحصة الأولى · 28 طالباً', present: 'حاضر', lateW: 'متأخر', absent: 'غائب', saveAtt: 'حفظ الحضور', attProgress: 'تم تسجيل 3 من 28',
  gradesTitle: 'إدخال الدرجات — اختبار الوحدة الثانية', thScore: 'الدرجة / 20', thGradeLabel: 'التقدير', excellent: 'ممتاز', veryGood: 'جيد جداً', pendingWord: 'بانتظار',
  tasksTitle: 'مهامي', task1: 'رصد درجات اختبار الوحدة الثانية', todayTag: 'اليوم', task2: 'إعداد خطة درس الأسبوع القادم', task3: 'تسليم تقرير حضور الأسبوع الماضي',
  annTitle: 'تعاميم الإدارة', ann1: 'اجتماع أولياء الأمور — الخميس 12 سبتمبر', ann1s: 'الحضور إلزامي لمعلمي المرحلة الابتدائية.', ann2: 'تحديث نموذج خطة الدرس', ann2s: 'النموذج الجديد متاح في قسم الملفات.',
  upcoming: 'القادم في التقويم الدراسي',
  parentName: 'محمد العتيبي', parentRole: 'وليّ أمر · نورة وسلمان',
  secChild: 'أبنائي', secParentSchool: 'المدرسة',
  pOverview: 'نظرة عامة', pGradesNav: 'الدرجات والتقارير', pAttNav: 'سجل الحضور', pFeesNav: 'الرسوم والفواتير', pAskNav: 'اسأل المعلم', pCalNav: 'التقويم الدراسي', pCircNav: 'التعاميم',
  pGreet: 'مرحباً، أبا نورة', pDay: 'الأحد 8 سبتمبر · لا يوجد غياب هذا الأسبوع · فاتورة واحدة مستحقة',
  childSwitch: 'الطالب المعروض', childB: 'سلمان · السادس (ب) · قسم البنين', childG: 'نورة · الرابع (أ) · قسم البنات',
  pKAtt: 'نسبة الحضور', pKAvg: 'المعدل العام', pKFees: 'المستحق', pKNext: 'القادم',
  pKAttV: '96%', pKAvgV: '91.5%', pKFeesV: '2,100 ر.س', pKNextV: 'اختبار الوحدة 2', pKAttS: 'يومان تأخر هذا الفصل', pKAvgS: '▲ 1.8 عن الفصل السابق', pKFeesS: 'يُستحق 20 سبتمبر', pKNextS: 'الأحد 15 سبتمبر',
  askTitle: 'اسأل المعلم', askSub: 'اطرح سؤالاً على معلم المادة مباشرة',
  askSlaBadge: 'يرد عادة خلال 24 ساعة', askSlaNote: 'متوسط زمن الرد لمعلمي الرابع (أ): 7 ساعات',
  askPickTeacher: 'اختر المعلم', askPickSubject: 'الموضوع', askQ: 'سؤالك',
  askQPh: 'اكتب سؤالك بوضوح — سيصل للمعلم فقط…', askSend: 'إرسال السؤال', askNote: 'الأسئلة تُرسل لمعلم القسم نفسه فقط، ولا تظهر لبقية أولياء الأمور.',
  askT1: 'أ. هند ناصر — رياضيات (رد خلال 4 ساعات)', askT2: 'أ. لمياء القرني — علوم (رد خلال 9 ساعات)', askT3: 'أ. ريما الحميد — وكيلة القسم (رد خلال 12 ساعة)',
  askS1: 'واجبات ودروس', askS2: 'الاختبارات والدرجات', askS3: 'الحضور والسلوك', askS4: 'أخرى',
  askMine: 'أسئلتي السابقة', askPendTag: 'بانتظار الرد', askAnsTag: 'تم الرد',
  aq1: 'هل توجد تمارين إضافية للقسمة الطويلة؟', aq1m: 'إلى أ. هند ناصر · قبل 3 ساعات', aq1r: 'يُتوقع الرد قبل 6:00 م اليوم',
  aq2: 'متى موعد اختبار الوحدة الثالثة؟', aq2m: 'إلى أ. لمياء القرني · أمس', aq2r: 'أ. لمياء: الاختبار الأحد 22 سبتمبر، والمراجعة يوم الخميس.',
  invTitle: 'الرسوم والفواتير', invSub: 'الفصل الدراسي الأول 1448هـ / 2026م',
  thInvoice: 'الفاتورة', thDue: 'الاستحقاق', thAmount: 'المبلغ', thStatus: 'الحالة',
  inv1: 'القسط الثاني — نورة · الفصل الأول 1448هـ / 2026م', inv1d: '20 سبتمبر', inv1a: '2,100 ر.س', inv2: 'القسط الأول — نورة · الفصل الأول 1448هـ / 2026م', inv2d: '5 أغسطس', inv2a: '2,100 ر.س', inv3: 'النقل المدرسي — الفصل الأول 1448هـ / 2026م', inv3d: '5 أغسطس', inv3a: '900 ر.س',
  invDue: 'مستحقة', invPaid: 'مسدّدة', payNow: 'سدّد الآن', invReceipt: 'إيصال',
  pGradesTitle: 'درجات نورة — الفصل الدراسي الأول 1448هـ / 2026م', thSubjectCol: 'المادة', thTermNow: 'الفصل الحالي', thTermPrev: 'الفصل السابق',
  pgMath: 'رياضيات', pgSci: 'علوم', pgAra: 'لغة عربية', pgEng: 'لغة إنجليزية',
  pAttTitle: 'سجل الحضور — آخر أسبوعين', attPresentDays: '9 حضور', attLateDays: 'تأخر يومان', attAbsentDays: 'لا غياب',
  msTitle: 'إضافة طالب جديد', msSub: 'البيانات المطلوبة لإنشاء ملف الطالب',
  mfName: 'الاسم الكامل', mfBirth: 'تاريخ الميلاد', mfGrade: 'الصف المطلوب', mfCampus: 'القسم', mfGuardian: 'اسم وليّ الأمر', mfGuardPhone: 'جوال وليّ الأمر', mfEmail: 'البريد الإلكتروني', mfPhoto: 'صورة الطالب',
  mtTitle: 'إضافة معلم جديد', mtSub: 'يُربط الحساب بقسم واحد فقط ولا يمكن تغييره لاحقاً إلا بموافقة الإدارة',
  mtName: 'الاسم الكامل', mtSubject: 'التخصص', mtCampus: 'القسم', mtPhone: 'رقم الجوال', mtEmail: 'البريد الإلكتروني', mtStart: 'تاريخ المباشرة', mtPhoto: 'الصورة الشخصية',
  reqTag: 'مطلوب', selectPh: 'اختر…', uploadHint: 'اسحب الصورة هنا أو اضغط للاختيار — JPG/PNG بحد 2 ميجابايت', browse: 'اختيار ملف',
  campusLockNote: 'القسم يحدد ما يراه المعلم: محادثة الكادر، الفصول، وأسئلة أولياء الأمور.',
  logout: 'تسجيل الخروج', myClsTitle: 'فصولي', myClsSub: 'الفصول المسندة إليك هذا الفصل الدراسي', thAvgCol: 'متوسط الفصل',
  clsTitle: 'إدارة الفصول والجداول', clsSub: 'توزيع الفصول والقاعات على القسمين', stagePri: 'ابتدائية', noHomeroom: 'بدون معلم فصل',
  thClass: 'الفصل', thStage: 'المرحلة', thHomeroom: 'معلم الفصل', thCount: 'عدد الطلاب', thRoom: 'القاعة',
  t3: 'لمياء القرني', t4: 'طلال المطيري',
  finTitle: 'فواتير الرسوم', kFinCollected: 'إجمالي المحصّل', kFinDue: 'المتأخرات', kFinRate: 'نسبة التحصيل', kFinOpen: 'فواتير معلّقة',
  vFinCollected: '1,148,600 ر.س', vFinDue: '96,400 ر.س', invOverdue: 'متأخرة', remind: 'تذكير',
  fi1: 'القسط الثاني — الرابع (أ)', fi1a: '2,100 ر.س', fi1d: '20 سبتمبر', fi2: 'القسط الثاني — السادس (ب)', fi2a: '2,400 ر.س', fi2d: '5 سبتمبر', fi3: 'النقل المدرسي — الثاني (ج)', fi3a: '900 ر.س', fi3d: '5 أغسطس',
  permsTitle: 'الأدوار والصلاحيات', permsSub: 'ما يستطيع كل دور الوصول إليه', thRole: 'الدور', roleDeputy: 'وكيل قسم', roleTeacher: 'معلم', roleAccountant: 'محاسب',
  genTitle: 'إعدادات عامة', genSub: 'إعدادات المجمع الأساسية', onWord: 'مُفعّل', offWord: 'موقوف',
  setLang: 'اللغة الافتراضية', setLangV: 'العربية (من اليمين إلى اليسار)', setYear: 'السنة الدراسية', setYearV: 'الفصل الدراسي الأول 1448هـ / 2026م',
  setNotif: 'تنبيهات البريد الإلكتروني', setNotifV: 'الفواتير والغياب والرسائل', setSep: 'فصل القسمين', setSepV: 'إجباري — لا يمكن تعطيله', addClass: '+ إضافة فصل', addInvoice: '+ إنشاء فاتورة', notRegistered: 'لا تملك حساباً؟', viewPublic: 'تصفّح الصفحة العامة', notBuilt: 'هذا القسم لم يُصمّم بعد — الشاشة محفوظة في التصميم وتحتاج محتوى قبل التسليم للتطوير.', backOverview: 'العودة للنظرة العامة', cancel: 'إلغاء', saveStudent: 'حفظ الطالب', saveTeacher: 'حفظ المعلم', closeAria: 'إغلاق'
};

const EN = {
  authNoLib: 'The database library did not load. Check your internet connection and reload the page.',
  authBadCreds: 'That email or password is not correct.', authUnconfirmed: 'This email is not confirmed yet — open the confirmation message in your inbox.', authRateLimit: 'Too many attempts in a row. Wait a moment and try again.', authOffline: 'Could not reach the server. Check your connection.', authFailed: 'Sign-in failed.', authMissing: 'Enter your email and password.', saving: 'Saving…', saveFailed: 'Could not save.', dbMissing: 'The database is not set up yet.',
  crumbAria: 'Breadcrumb',
  mock: 'Screens', navVisitor: 'Public Page', navLogin: 'Login', navAdmin: 'Admin', navStaff: 'Staff', navParent: 'Parent',
  stLoading: 'Loading state', stEmpty: 'Empty state', stStudent: 'Add Student modal', stTeacher: 'Add Teacher modal',
  brand: 'Nasr School Complex', brandSub: 'Separate boys & girls campuses · KG — Grade 12',
  mAbout: 'About', mLevels: 'Levels & Campuses', mFees: 'Fees', mContact: 'Contact', loginCtaShort: 'Parent & staff login',
  vBadge: 'Admissions open for 1448 AH / 2026 AD',
  vTitle: 'Rigorous learning in a well-run school — a dedicated campus for every stage',
  vText: 'Nasr School Complex operates two fully separate campuses for boys and girls, each with its own building, teaching staff and administration, from kindergarten through grade 12.',
  vApply: 'Apply / Inquire', vBrochure: 'Download brochure',
  vStudents: 'students enrolled', vStaff: 'teaching staff', vYears: 'years of service', vClasses: 'classes',
  imgMain: 'Main building photo — [ drop a wide, high-res image here ]',
  boys: 'Boys Campus', girls: 'Girls Campus',
  boysText: 'A separate building with male teaching and administrative staff, dedicated sports facilities and science labs.',
  girlsText: 'A separate building with female teaching and administrative staff, dedicated activity halls and computer labs.',
  lvlKgB: 'Kindergarten · Boys', lvlKgG: 'Kindergarten · Girls', lvlPri: 'Primary (1 — 6)', lvlMid: 'Middle (7 — 9)', lvlHigh: 'High (10 — 12)',
  quick: 'Key information', qDay: 'School day', qBus: 'School transport', qBusV: 'All districts covered', qSize: 'Students per class', qSizeV: '28 maximum', qFees: 'Annual fees', qFeesV: 'From SAR 8,400',
  applyTitle: 'Apply or send an inquiry',
  applyText: 'Send us your details and the admissions team will contact you within one working day to arrange a campus visit.',
  contactTitle: 'Contact information', contactPhone: 'Admissions: 011 456 7890', contactMail: 'Email: info@nasr.edu.sa', contactAddr: 'King Abdulaziz Rd, Al Nakheel, Riyadh',
  mapPh: 'Location map — [ interactive map ]',
  fName: 'Your full name', fNamePh: 'Mohammed Al-Otaibi', fPhone: 'Mobile number', fAge: "Child's age", fAgePh: '9 years', fCampus: 'Preferred campus',
  fMsg: 'Your message or question', fMsgPh: 'I would like information about grade 4 admissions…', fConsent: 'I agree to be contacted about this application', fSubmit: 'Submit request',
  haveAcc: 'Already have an account?', loginWord: 'Log in',
  footerRights: '© 1448 AH / 2026 AD Nasr School Complex — All rights reserved', privacy: 'Privacy policy', jobs: 'Careers',
  lTitle: 'One platform for students, teachers and parents', lText: 'Attendance, grades, timetables and tuition — in one secure, organised place.',
  loginTitle: 'Log in', loginSub: 'Choose your account type, then enter your credentials',
  roleAdmin: 'Admin', roleStaff: 'Teacher / Staff', roleParent: 'Parent',
  emailLabel: 'Email or national ID', pwLabel: 'Password', remember: 'Remember me', forgot: 'Forgot password?',
  loginCta: 'Log in to dashboard', loginNote: 'You will be redirected automatically based on the selected account type.',
  secAdmin: 'Administration', mOverview: 'Overview', mStudents: 'Students', mStaffNav: 'Teachers & staff', mClasses: 'Classes & timetables', mReports: 'Reports & analytics', mFinance: 'Fees & finance', mCalendarNav: 'Academic calendar', mLogNav: 'Activity log', secSystem: 'System', mSettings: 'Settings & permissions',
  adminName: 'Abdullah Al-Salem', adminRole: 'Complex principal',
  ovTitle: 'Overview', termLine: 'Term 1 · 1448 AH / 2026 AD', searchPh: 'Search students or teachers…', addStudent: '+ Add student',
  notifTitle: 'Notifications', nb1: '23 invoices are overdue', nb1s: 'Finance · 1 hour ago', nb2: '7 absences today need follow-up', nb2s: 'Attendance · 3 hours ago', nb3: '4 parent questions await a reply', nb3s: 'Messages · today', notifAll: 'View all notifications',
  kStudents: 'Total students', kStaff: 'Teachers & staff', kClasses: 'Classes', kRevenue: 'Term revenue',
  tStudents: '▲ 3.2% vs last month', tStaff: '4 open positions', tClasses: '30 students per class avg.', tRevenue: 'Outstanding: SAR 96,400', millionUnit: 'M SAR',
  attTitle: 'Weekly attendance rate', attAvg: '94% average', sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu',
  alerts: 'Alerts needing action', al1: '23 invoices are overdue', al1s: 'SAR 96,400 total — finance review required', al2: '7 new enrolment requests', al2s: 'Awaiting administration approval', al3: 'Two classes without cover tomorrow', al3s: 'Grade 4 (B) · Grade 6 (A)', allAlerts: 'View all alerts',
  qaTitle: 'Parent questions oversight', qaSub: 'Aggregated per campus — administration does not enter staff chats', qaReport: 'Full communication report',
  qaPendBoys: 'Pending — Boys campus', qaPendGirls: 'Pending — Girls campus', qaAvgTime: 'Average reply time', qaOver: 'Over 24 hours', hoursUnit: ' hours',
  calTitle: 'Academic calendar', calSub: 'Holidays, exams and events — September / October', calFull: 'Full calendar',
  tHoliday: 'Holiday', tExam: 'Exam', tEvent: 'Event',
  ev1: 'Parents meeting', ev1d: 'Thu 12 Sep · 5 — 7 PM', ev2: 'Unit 2 examinations', ev2d: 'Sun 15 — Wed 18 Sep', ev3: 'National Day — official holiday', ev3d: 'Wed 23 Sep', ev4: 'Science museum trip', ev4d: 'Mon 5 Oct · Boys campus',
  cmpTitle: 'Comparative analytics', cmpSub: 'Boys vs girls campus · current vs previous term',
  cmpAvg: 'Average grade', cmpAtt: 'Attendance rate', cmpPass: 'Pass rate', cmpTermNow: 'Current term', cmpTermPrev: 'Previous term', exportPdf: 'Export PDF', exportXls: 'Export Excel',
  staffMgmt: 'Teacher & staff management', staffMgmtSub: 'Both campuses are administered separately', boysCount: 'Boys campus (41)', girlsCount: 'Girls campus (45)', addTeacher: '+ Add teacher',
  thTeacher: 'Teacher', thSubject: 'Subject', thCampus: 'Campus', thClassesCol: 'Classes', thActions: 'Actions', edit: 'Edit', del: 'Delete',
  t1: 'Khalid Abdulrahman Al-Shamri', t2: 'Hind Nasser Al-Zahrani', subjScience: 'Science', subjMath: 'Mathematics', cls5: '5 classes', cls6: '6 classes', tagBoys: 'Boys', tagGirls: 'Girls',
  recent: 'Recently enrolled students', fAll: 'All', fPri: 'Primary', fMid: 'Middle',
  thStudent: 'Student', thGradeCol: 'Class', thGuardian: 'Guardian', thFeesCol: 'Fee status',
  s1: 'Noura Mohammed Al-Otaibi', s2: 'Salman Abdulaziz Al-Qahtani', s3: 'Reem Fahd Al-Dosari', g1: 'Mohammed Al-Otaibi', g2: 'Abdulaziz Al-Qahtani', g3: 'Fahd Al-Dosari',
  gr4a: 'Grade 4 (A)', gr6b: 'Grade 6 (B)', gr2c: 'Grade 2 (C)', paid: 'Paid', lateFee: 'Instalment overdue', underReview: 'Under review',
  loadingStudents: 'Loading student records…', emptyTitle: 'No matching results', emptyText: 'No students match these filters. Try a different level, or add a new student to get started.',
  logTitle: 'Admin activity log', logSub: 'Who changed what, and when', logAll: 'Full log',
  lg1: 'Abdullah Al-Salem', lg1w: 'updated fees for Grade 6 (B)', lg1t: 'Today 10:42 AM', lg2: 'Rima Al-Hamid', lg2w: 'added a teacher to the girls campus', lg2t: 'Today 09:15 AM', lg3: 'Talal Al-Mutairi', lg3w: 'exported the boys campus attendance report', lg3t: 'Yesterday 01:20 PM',
  secDaily: 'Daily', mMySchedule: 'My schedule', mAttendance: 'Mark attendance', mGradesNav: 'Enter grades', mMyClasses: 'My classes', secComms: 'Communication', mMessages: 'Messages & circulars', mParentQ: 'Parent questions', mTasks: 'My tasks',
  chatSecGirls: 'Campus chat — Girls', chatGirlsNav: 'Girls campus staff chat', noteGirls: 'Your account belongs to the girls campus — the boys campus chat is not available.',
  chatSecBoys: 'Campus chat — Boys', chatBoysNav: 'Boys campus staff chat', noteBoys: 'Your account belongs to the boys campus — the girls campus chat is not available.',
  staffNameG: 'Hind Nasser', staffRoleG: 'Maths teacher · Girls campus', staffNameB: 'Khalid Al-Shamri', staffRoleB: 'Science teacher · Boys campus',
  greetG: 'Good morning, Hind', greetB: 'Good morning, Khalid', staffDay: 'Sunday 8 September · 4 lessons today, 1 class still needs attendance', markNow: 'Mark attendance for current lesson',
  weekTitle: 'This week', lessonsWeek: '20 lessons per week',
  subjMathShort: 'Maths', freePeriod: 'Free period', breakDuty: 'Break duty', deptMeeting: 'Department meeting', mathActivity: 'Maths activity',
  cls4a: 'Grade 4 (A)', cls4b: 'Grade 4 (B)', cls5a: 'Grade 5 (A)', cls5b: 'Grade 5 (B)', cls6a: 'Grade 6 (A)', cls6b: 'Grade 6 (B)',
  pqTitle: 'Parent questions', pqPending: '4 pending', pqTabPending: 'Pending', pqTabAnswered: 'Answered', pqSla: 'Your expected reply time: within 24 hours',
  pq1: 'Mohammed Al-Otaibi', pq1meta: "Noura's guardian · Grade 4 (A)", pq1txt: 'Are there extra long-division exercises we can work on at home?', pq1st: 'Pending · 3 hours',
  pq2: 'Fahd Al-Dosari', pq2meta: "Reem's guardian · Grade 2 (C)", pq2txt: 'When is the unit 3 test scheduled?', pq2st: 'Pending · 11 hours',
  pq3: 'Suad Al-Qahtani', pq3meta: "Lama's guardian · Grade 5 (B)", pq3txt: 'Thank you for clarifying the weekly homework.', pq3st: 'Answered',
  pqReply: 'Reply', pqEscalate: 'Escalate to admin',
  chatGTitle: 'Girls Campus Staff Chat', chatGSub: '14 members · girls campus staff only',
  cg1n: 'Ms. Lamya Al-Qarni', cg1m: 'Good morning — the unit test invigilation rota is on the department board.', cg2n: 'Ms. Rima Al-Hamid — deputy head', cg2m: 'Reminder: grade entry closes tomorrow at 2 PM.', cgMe: 'Noted — I will finish Grade 4 (A) today.', chatGPh: 'Message the girls campus staff…',
  chatBTitle: 'Boys Campus Staff Chat', chatBSub: '12 members · boys campus staff only',
  cb1n: 'Mr. Khalid Al-Shamri', cb1m: 'The science lab is booked for period 3 today.', cb2n: 'Mr. Talal Al-Mutairi — deputy head', cb2m: 'Who can cover Grade 6 (A) tomorrow?', cbMe: 'I can cover it — my second period is free.', chatBPh: 'Message the boys campus staff…',
  me: 'Me', send: 'Send',
  attMark: 'Attendance —', incomplete: 'Incomplete', period1: 'Period 1 · 28 students', present: 'Present', lateW: 'Late', absent: 'Absent', saveAtt: 'Save attendance', attProgress: '3 of 28 recorded',
  gradesTitle: 'Grade entry — Unit 2 test', thScore: 'Score / 20', thGradeLabel: 'Grade', excellent: 'Excellent', veryGood: 'Very good', pendingWord: 'Pending',
  tasksTitle: 'My tasks', task1: 'Enter unit 2 test scores', todayTag: 'Today', task2: 'Prepare next week lesson plan', task3: 'Submit last week attendance report',
  annTitle: 'Circulars from administration', ann1: 'Parents meeting — Thursday 12 September', ann1s: 'Attendance is mandatory for primary teachers.', ann2: 'Lesson plan template updated', ann2s: 'The new template is available in Files.',
  upcoming: 'Coming up in the academic calendar',
  parentName: 'Mohammed Al-Otaibi', parentRole: 'Guardian · Noura & Salman',
  secChild: 'My children', secParentSchool: 'School',
  pOverview: 'Overview', pGradesNav: 'Grades & reports', pAttNav: 'Attendance record', pFeesNav: 'Fees & invoices', pAskNav: 'Ask the teacher', pCalNav: 'Academic calendar', pCircNav: 'Circulars',
  pGreet: 'Welcome, Mohammed', pDay: 'Sunday 8 September · no absences this week · 1 invoice due',
  childSwitch: 'Viewing', childB: 'Salman · Grade 6 (B) · Boys campus', childG: 'Noura · Grade 4 (A) · Girls campus',
  pKAtt: 'Attendance rate', pKAvg: 'Average grade', pKFees: 'Outstanding', pKNext: 'Coming up',
  pKAttV: '96%', pKAvgV: '91.5%', pKFeesV: 'SAR 2,100', pKNextV: 'Unit 2 test', pKAttS: '2 late arrivals this term', pKAvgS: '▲ 1.8 vs previous term', pKFeesS: 'Due 20 September', pKNextS: 'Sunday 15 September',
  askTitle: 'Ask the teacher', askSub: 'Send a question straight to the subject teacher',
  askSlaBadge: 'Usually replies within 24 hours', askSlaNote: 'Average reply time for Grade 4 (A) teachers: 7 hours',
  askPickTeacher: 'Choose a teacher', askPickSubject: 'Topic', askQ: 'Your question',
  askQPh: 'Write your question clearly — only the teacher will see it…', askSend: 'Send question', askNote: 'Questions go only to a teacher on the same campus and are never visible to other parents.',
  askT1: 'Ms. Hind Nasser — Maths (replies in ~4 h)', askT2: 'Ms. Lamya Al-Qarni — Science (replies in ~9 h)', askT3: 'Ms. Rima Al-Hamid — Deputy head (replies in ~12 h)',
  askS1: 'Homework & lessons', askS2: 'Tests & grades', askS3: 'Attendance & behaviour', askS4: 'Other',
  askMine: 'My previous questions', askPendTag: 'Awaiting reply', askAnsTag: 'Answered',
  aq1: 'Are there extra long-division exercises?', aq1m: 'To Ms. Hind Nasser · 3 hours ago', aq1r: 'Reply expected before 6:00 PM today',
  aq2: 'When is the unit 3 test scheduled?', aq2m: 'To Ms. Lamya Al-Qarni · yesterday', aq2r: 'Ms. Lamya: the test is on Sunday 22 September, with revision on Thursday.',
  invTitle: 'Fees & invoices', invSub: 'Term 1 · 1448 AH / 2026 AD',
  thInvoice: 'Invoice', thDue: 'Due date', thAmount: 'Amount', thStatus: 'Status',
  inv1: 'Instalment 2 — Noura · term 1, 1448 AH / 2026 AD', inv1d: '20 September', inv1a: 'SAR 2,100', inv2: 'Instalment 1 — Noura · term 1, 1448 AH / 2026 AD', inv2d: '5 August', inv2a: 'SAR 2,100', inv3: 'School transport — term 1, 1448 AH / 2026 AD', inv3d: '5 August', inv3a: 'SAR 900',
  invDue: 'Due', invPaid: 'Paid', payNow: 'Pay now', invReceipt: 'Receipt',
  pGradesTitle: "Noura's grades — term 1, 1448 AH / 2026 AD", thSubjectCol: 'Subject', thTermNow: 'Current term', thTermPrev: 'Previous term',
  pgMath: 'Mathematics', pgSci: 'Science', pgAra: 'Arabic', pgEng: 'English',
  pAttTitle: 'Attendance record — last two weeks', attPresentDays: '9 present', attLateDays: '2 late', attAbsentDays: 'No absences',
  msTitle: 'Add a new student', msSub: 'Details required to create the student record',
  mfName: 'Full name', mfBirth: 'Date of birth', mfGrade: 'Class requested', mfCampus: 'Campus', mfGuardian: 'Guardian name', mfGuardPhone: 'Guardian mobile', mfEmail: 'Email address', mfPhoto: 'Student photo',
  mtTitle: 'Add a new teacher', mtSub: 'The account is tied to one campus only and cannot be changed later without administration approval',
  mtName: 'Full name', mtSubject: 'Subject', mtCampus: 'Campus', mtPhone: 'Phone number', mtEmail: 'Email address', mtStart: 'Start date', mtPhoto: 'Profile photo',
  reqTag: 'Required', selectPh: 'Select…', uploadHint: 'Drop an image here or click to choose — JPG/PNG up to 2 MB', browse: 'Choose file',
  campusLockNote: 'The campus decides what the teacher sees: staff chat, classes and parent questions.',
  logout: 'Log out', myClsTitle: 'My classes', myClsSub: 'Classes assigned to you this term', thAvgCol: 'Class average',
  clsTitle: 'Classes & schedules', clsSub: 'Class and room allocation across both campuses', stagePri: 'Primary', noHomeroom: 'No homeroom teacher',
  thClass: 'Class', thStage: 'Stage', thHomeroom: 'Homeroom teacher', thCount: 'Students', thRoom: 'Room',
  t3: 'Lamya Al-Qarni', t4: 'Talal Al-Mutairi',
  finTitle: 'Fee invoices', kFinCollected: 'Total collected', kFinDue: 'Outstanding', kFinRate: 'Collection rate', kFinOpen: 'Open invoices',
  vFinCollected: 'SAR 1,148,600', vFinDue: 'SAR 96,400', invOverdue: 'Overdue', remind: 'Remind',
  fi1: 'Instalment 2 — Grade 4 (A)', fi1a: 'SAR 2,100', fi1d: '20 September', fi2: 'Instalment 2 — Grade 6 (B)', fi2a: 'SAR 2,400', fi2d: '5 September', fi3: 'School transport — Grade 2 (C)', fi3a: 'SAR 900', fi3d: '5 August',
  permsTitle: 'Roles & permissions', permsSub: 'What each role can reach', thRole: 'Role', roleDeputy: 'Deputy head', roleTeacher: 'Teacher', roleAccountant: 'Accountant',
  genTitle: 'General settings', genSub: 'Core complex configuration', onWord: 'On', offWord: 'Off',
  setLang: 'Default language', setLangV: 'Arabic (right-to-left)', setYear: 'Academic year', setYearV: 'Term 1 · 1448 AH / 2026 AD',
  setNotif: 'Email notifications', setNotifV: 'Invoices, absences and messages', setSep: 'Campus separation', setSepV: 'Enforced — cannot be disabled', addClass: '+ Add class', addInvoice: '+ Create invoice', notRegistered: 'No account yet?', viewPublic: 'Browse the public page', notBuilt: 'This section has not been designed yet — the screen is reserved in the design and needs content before development handoff.', backOverview: 'Back to overview', cancel: 'Cancel', saveStudent: 'Save student', saveTeacher: 'Save teacher', closeAria: 'Close'
};

window.NasrI18n = { ar: AR, en: EN };
